- hosts: NOME_DO_CLIENTE
  gather_facts: no
  tasks:
    - name: Pesquisando o arquivo no SIEM e salvando sua saida 
      shell: (cd /opt/rules/export/; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: files_to_copy

    - name: Copiando o arquivo para a aplicação
      fetch:
        src: /opt/rules/export/{{ item }}
        dest: /opt/rundeck/git/lab/
        flat: true
      with_items: "{{ files_to_copy.stdout_lines }}"

    - name: Pesquisando o arquivo no SIEM e salvando sua saida 
      shell: (cd /opt/rules/export/; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: files_to_copy

    - name: Copiando o arquivo para a aplicação
      fetch:
        src: /opt/rules/export/{{ item }}
        dest: /opt/rundeck/git/lab/
        flat: true
      with_items: "{{ files_to_copy.stdout_lines }}"
