- name: Playbook que executa o export das regras
  hosts: NOME_DO_CLIENTE
  gather_facts: no
  tasks:
  - name: "Exportando a regra"
    shell: cd /opt/rules/export && rm -rf * && /opt/qradar/bin/contentManagement.pl -a export --content-type 3 --regex "^NOME_DA_REGRA*" | tee new_rule
  - name: "Extraindo os arquivos"
    shell: cd /opt/rules/export && unzip `grep SUCCESS new_rule | cut -d"/" -f5`
  - name: "Excluindo arquivos não utilizados"
    shell: cd /opt/rules/export && rm -rf *.zip && rm -rf new_rule
  - name: "Renomeando o arquivo "
    shell: mv * "^NOME_DA_REGRA*"
###
